[site]
bucket = "./"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/*.wasm"
[headers.values]
Content-Type = "application/wasm"

[[headers]]
for = "/*.bin"
[headers.values]
Content-Type = "application/octet-stream"
